### ISSUE TITLE
Fake Acrylic Background Picker NRE

### ISSUE THREAD

**Issue by Techttv** [krlvm/BeautySearch#14]
When I try to install BeautySearch an .net framework error show up.

Log: 
`Le informazioni su come richiamare il debug JIT (Just-In-Time) anziché questa finestra
sono riportate in fondo al messaggio.

************** Testo dell'eccezione **************
System.NullReferenceException: Riferimento a un oggetto non impostato su un'istanza di oggetto.
   in BeautySearch.FakeBackgroundAcrylic.IsSearchBoxVisible()
   in BeautySearch.FakeBackgroundAcrylic.CaptureWallpaper(String directory)
   in BeautySearch.ScriptInstaller.Install(FeatureControl features)
   in BeautySearch.InstallationForm.installBtn_Click(Object sender, EventArgs e)
   in System.Windows.Forms.Control.OnClick(EventArgs e)
   in System.Windows.Forms.Button.OnClick(EventArgs e)
   in System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   in System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   in System.Windows.Forms.Control.WndProc(Message& m)
   in System.Windows.Forms.ButtonBase.WndProc(Message& m)
   in System.Windows.Forms.Button.WndProc(Message& m)
   in System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   in System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Assembly caricati **************
mscorlib
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4390.0 built by: NET48REL1LAST_C
    Base di codice: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
BeautySearch
    Versione assembly: 1.6.0.0
    Versione Win32: 1.6.0.0
    Base di codice: file:///C:/Users/tomma/Downloads/BeautySearch%20(1).exe
----------------------------------------
System.Windows.Forms
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4390.0 built by: NET48REL1LAST_C
    Base di codice: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4360.0 built by: NET48REL1LAST_C
    Base di codice: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4390.0 built by: NET48REL1LAST_C
    Base di codice: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4190.0 built by: NET48REL1LAST_B
    Base di codice: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4390.0 built by: NET48REL1LAST_C
    Base di codice: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4084.0 built by: NET48REL1
    Base di codice: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Management
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4084.0 built by: NET48REL1
    Base di codice: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
System.Web
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4330.0 built by: NET48REL1LAST_B
    Base di codice: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
mscorlib.resources
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4084.0 built by: NET48REL1
    Base di codice: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_it_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4084.0 built by: NET48REL1
    Base di codice: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_it_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** Debug JIT **************
Per abilitare il debug JIT, è necessario impostare il valore
jitDebugging nella sezione system.windows.forms del file di configurazione
dell'applicazione o del computer (machine.config).
L'applicazione inoltre deve essere compilata con il debug
abilitato.

Ad esempio:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Quando il debug JIT è abilitato, tutte le eccezioni non gestite
vengono inviate al debugger JIT registrato nel computer,
anziché essere gestite da questa finestra di dialogo.`

https://user-images.githubusercontent.com/62478271/128761630-e4eb1387-498a-46b9-a53d-917c030ac62e.mp4

**Comment by krlvm** [comment]
Thanks for details, that happens because BeautySearch can't unlock Search files to modify it (it actually just one .html file, no DLLs are patched), take ownership over `C:\Windows\SystemApps\Microsoft.Windows.Search_cw5n1h2txyewy\cache\Local\Desktop\2.html` as descirbed [here](https://github.com/krlvm/BeautySearch/issues/11#issuecomment-860113080) and try again - it will work.

**Comment by Techttv** [comment]
I tried but the same error show up :/

**Comment by Techttv** [comment]
Same error.

https://user-images.githubusercontent.com/62478271/128764499-54e14419-7cc2-4d03-b3e1-68cd0a435def.mp4

**Comment by krlvm** [comment]
Sorry for oversight, it appears the problem with Fake Acrylic: the installer can't determine whether search box visible on taskbar or not. Try to changing it's state via taskbar context menu (hide it, then show it again), or check the registry key: `HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Search`, DWORD `SearchboxTaskbarMode`

**Comment by Techttv** [comment]
Ok now it does work. thx.

**Comment by krlvm** [comment]
Should be fixed in [version 1.6.1](https://github.com/krlvm/BeautySearch/releases/tag/v1.6.1), please check does it work for you.
