### ISSUE TITLE
Top apps looks weird!

### ISSUE THREAD

**Issue by HuyHung1408** [krlvm/BeautySearch#16]
I don't think it looks good. The icon size is too big
![image](https://user-images.githubusercontent.com/86362423/138548916-3e1db076-8a5c-4627-81a0-1995c26e187b.png)

**Comment by krlvm** [comment]
With [version 1.9](https://github.com/krlvm/BeautySearch/releases/tag/v1.9) BeautySearch allows you to reorder Top Apps, so you can get rid of these ugly/useless icons.

**Comment by HuyHung1408** [comment]
Much thanks!
