### ISSUE TITLE
Can the icon on the right-click menu match with the system icon? 

### ISSUE THREAD

**Issue by HuyHung1408** [krlvm/BeautySearch#18]
Can the icon on the right-click menu change into Fluent System Design icon? This is just my own thinking and question

# This is the fluent system icon in my Windows 10
![image](https://user-images.githubusercontent.com/86362423/143457711-406506dd-dfcf-4419-a997-391717618cce.png)

# The right-click menu is using the old MDL2 assets icon
It does not match the rest of my Windows 10 icon
![image](https://user-images.githubusercontent.com/86362423/143456333-94db897e-826c-401e-ad0c-258f34525e4c.png)

**Comment by krlvm** [comment]
You've installed the new Segoe Fluent Icons font?
These icons are actually being retrieved from "Segoe MDL2 Assets" font, where Windows 11 assets font is named "Segoe Fluent Icons".
There's actually a new version of Segoe MDL2 Assets, which features those icons:
[Segoe MDL2 Assets v2.zip](https://github.com/krlvm/BeautySearch/files/7604096/Segoe.MDL2.Assets.v2.zip)

**Comment by HuyHung1408** [comment]
Yes, I've installed the new version of the font, but the right-click menu in Search is still old icons

**Comment by krlvm** [comment]
After additional reverse-engineering, I found that is does use Segoe MDL2 Assets, but the new icons are still not applied (except for unpin app icon). Unfortunately, I don't think it's possible to do something with that.

**Comment by HuyHung1408** [comment]
> You've installed the new Segoe Fluent Icons font?
> These icons are actually being retrieved from "Segoe MDL2 Assets" font, while Windows 11 assets font is named "Segoe Fluent Icons".
> There's actually a new version of Segoe MDL2 Assets, which features those icons:
> [Segoe MDL2 Assets v2.zip](https://github.com/krlvm/BeautySearch/files/7604096/Segoe.MDL2.Assets.v2.zip)
> 
>  
Okay thanks a lot

**Comment by HuyHung1408** [comment]
> After additional reverse-engineering, I found that is does use Segoe MDL2 Assets, but the new icons are still not applied (except for unpin app icon). Unfortunately, I don't think it's possible to do something with that.

Okay thanks a lot
