### ISSUE TITLE
Looks wired when searching above other application.

### ISSUE THREAD

**Issue by PIndividual** [krlvm/BeautySearch#19]
![image](https://user-images.githubusercontent.com/62368342/147853813-c60abf7b-37da-4e42-8fda-59c5fc9b2d3f.png)
when there are other applications opened under the search box, it still shows the desktop background as the Acrylic effect.

**Comment by HuyHung1408** [comment]
Because that's how it works. It captures a part of your desktop and uses that picture as a background to create a fake Acrylic effect. So that's why they called it "Fake Acrylic" instead of Enable Acrylic again. 
They have mentioned this 

> Search Window Acrylic effect was broken in late 20H1 Insider Builds and apparently won't be fixed, although a fix was already available in Build 19541. BeautySearch has a special Fake Acrylic tweak which re-implements the acrylic effect in a different way with some ***limitations***

**Comment by PIndividual** [comment]
That's reasonable, then I guess this won't be an issue anymore, thanks.

**Comment by krlvm** [comment]
I see Microsoft has finally fixed this bug in the upcoming cumulative update ([.1618](https://blogs.windows.com/windows-insider/2022/03/14/releasing-windows-10-build-19044-1618-to-release-preview-channel/)), which is currently available in Release Preview, so Search Window has native acrylic effect again - there is no longer need in Fake Acrylic mode.

I've released a [new version of BeautySearch](https://github.com/krlvm/BeautySearch/releases/tag/v1.10), which adds support for this build - after you install the update .1618 and reinstall BeautySearch, you will get real acrylic effect.

**Comment by PIndividual** [comment]
AWSOME! I'll check that out
