### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by bobf32** [krlvm/BeautySearch#2]
One error which appeared only the first time I tried to install (no I didn't save the text :o). Since then have done multiple installs and uninstalls separated with restarts, with no apparent errors . Search window background always appears unchanged i.e. white.

**Comment by bobf32** [comment]
I've added the reg key, still not working. My build is 19041.450.

**Comment by krlvm** [comment]
It usually installs without any problems, try to turn off the Internet connection and [restart Search app](https://github.com/krlvm/BeautySearch/issues/2#issuecomment-678694393).

I've tested it on builds 19041 and 19042 a few minutes ago.
![Screenshot 2020-08-23 221248](https://user-images.githubusercontent.com/51774833/90986747-db436d00-e58d-11ea-8973-9021c417025b.png)

**Comment by krlvm** [comment]
It usually installs without any problems, try to turn off the Internet connection and [restart Search app](https://github.com/krlvm/BeautySearch/issues/2#issuecomment-678694393).

I've tested it on builds 19041 and 19042 a few minutes ago.
![Screenshot 2020-08-23 221248_LI](https://user-images.githubusercontent.com/51774833/90986799-2eb5bb00-e58e-11ea-8b96-6c469c84d435.jpg)

**Comment by Gryzle** [comment]
I know this is a super old thread but for anyone who might be experiencing this issue (I was), go to:
`Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Search`
and set `CortanaConsent` to `0`. This should also work on older versions of windows, at the time of writing this, I'm on Windows 10 20H2, build 19042.804.
