### ISSUE TITLE
A small bug about the user's name

### ISSUE THREAD

**Issue by HTC-Group** [krlvm/BeautySearch#23]
My profile name is shown as "Enderturtle", but my ProfileImagePath is "houch".
It seems BeautySearch doesn't use the ProfileImagePath to get the true path.

![image](https://user-images.githubusercontent.com/45251727/155451090-19777164-5496-4460-9482-c874a3f9866f.png)

![image](https://user-images.githubusercontent.com/45251727/155451102-df887848-4d0a-4be0-9b8c-406aa7e22593.png)

**Comment by krlvm** [comment]
It actually uses `%LocalAppData%` environment variable, you need to correct it since it is not an expected use case.

**Comment by HTC-Group** [comment]
@krlvm I’m sorry to interrupt you. But actually, %LocalAppData% points to the correct path.
I do not know how to correct it in this case.
![image](https://user-images.githubusercontent.com/45251727/155512194-e0f42daf-3489-4beb-881e-9beee23fb8b5.png)

**Comment by krlvm** [comment]
Does this build fix the issue?
[BeautySearch.zip](https://github.com/krlvm/BeautySearch/files/8132154/BeautySearch.zip)

**Comment by HTC-Group** [comment]
Now it works! Thanks very much!
