### ISSUE TITLE
Unable to revert back to themed search menu

### ISSUE THREAD

**Issue by thecloakmaster** [krlvm/BeautySearch#30]
![image](https://user-images.githubusercontent.com/51017498/191189817-99bbff02-f227-45f8-b49f-35354181e582.png)
I tried uninstalling BeautySearch but it doesn't remove this. Any way I can manually get the red search background back?

**Comment by krlvm** [comment]
This is a feature of recent Windows 10 builds which came with 1904X.1618+. There's no way to disable it.
Someone has already asked it, so I implemented a tweak which disables it (uncheck `Show accent color on Search Window when it is shown on Start`), but you will need to install BeautySearch.

**Comment by thecloakmaster** [comment]
It used to be red before I tried to install BeautySearch however. The installation of BeautySearch failed and it changed to default dark mode.

**Comment by krlvm** [comment]
You mean the right side is being black?
It happened after recent Windows 10 CU, I fixed in the latest BeautySearch version.

**Comment by thecloakmaster** [comment]
Any idea what I need to edit in the system files to get it back?

**Comment by krlvm** [comment]
If you want to achieve this, it is enough to install the latest version of BeautySearch with default configuration.
![image](https://user-images.githubusercontent.com/51774833/191238463-8e9c3932-6b7d-462e-a202-42dff54b2714.png)

On which Windows 10 build you are on?
