### ISSUE TITLE
Bitdefender detects it as suspicious activity

### ISSUE THREAD

**Issue by leonborin** [krlvm/BeautySearch#31]
Bitdefender antivirus has a module called Advanced Threat Defense that blocks any application that writes to the system as the module treats it as malware.

![image](https://user-images.githubusercontent.com/95956843/194356810-008b9dcd-75ac-451b-a520-28989bd36cb8.png)
![image](https://user-images.githubusercontent.com/95956843/194356979-33784e8a-c18f-48f4-a122-77d5620f4b89.png)

**Comment by krlvm** [comment]
You answered your own question: the program overwrites the system file in the system search application folder (C\Windows\SystemApps\...), which is considered malicious activity by antiviruses, unfortunately I can’t do anything with this. You can build the application from sources yourself.

**Comment by leonborin** [comment]
I will try the manual installation way. But since I am using Windows 11 22H2 which the tweak touchs the Windows Feature Experience Pack, I might have to give up as my previous attempt not just trigger the key function of the antivirus (which will complain when that function turned off), also broke the search in which I have to reboot, then run sfc, dism restorehealth and sfc again to fix the search function. I think this method for Windows 11 is much more riskier than the tweak for 10.

**Comment by krlvm** [comment]
Nothing fundamentally changed in Search since Windows 10, except it has moved to a different package.

You can temporarily disable your antivirus and try again.

**Comment by leonborin** [comment]
The BeautySearch app also throws out unknown error and reported error as below after several reinstall attempts, so I solved by using manual method.

`Faulting application name: BeautySearch.exe, version: 1.15.0.0, time stamp: 0xce4209b5;
Faulting module name: KERNELBASE.dll, version: 10.0.22621.608, time stamp: 0x4769d08d;
Exception code: 0xe0434352;
Fault offset: 0x000000000008fb0c;
Faulting process id: 0x0x361C;
Faulting application start time: 0x0x1D8D99F669A73FA;
Faulting application path: C:\Users\Leon\Downloads\BeautySearch.exe;
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll;
Report Id: 39edd487-327d-42cc-bab9-ba60b88a8ad1;
`

Here is which I manage to get this done using manual method:
Step 1: Copy the original `2.html` from `C:\Windows\SystemApps\MicrosoftWindows.Client.CBS_cw5n1h2txyewy\Cortana.UI\cache\SVLocal\Desktop` to another user folder (e.g. downloads folder)
Step 2: Edit the `2.html` using text editor by adding this code `<script type="text/javascript" src="ms-appx-web:///Cortana.UI/cache/svlocal/desktop/BeautySearch.js"></script>` at the last line. Note that the original code contains some backslashes `\` which need to be removed manually if copy from there. Otherwise, the code will not work.
Step 3: Save the edited html as a copy with another name (will rename it at the step 8)
Step 4: Go to the readme file of the main GitHub page, right click onto the Windows 11 script link and use save as function. Then rename it as `BeautySearch.js` in this case I will retain the default settings in the script.
Step 5: Copy both edited html and JS file into `C:\Windows\SystemApps\MicrosoftWindows.Client.CBS_cw5n1h2txyewy\Cortana.UI\cache\SVLocal\Desktop`
Step 6: Take over the folder permission. I prefer to change owner to `Administrators`, then give `Administrators` full control over the folder and files within.
Step 7: Rename `2.html` to `2.html.bak` (if skipped Step 6 or didn't do Step 6 properly, will fail to rename this file, so this is a check whether Step 6 is done properly)
Step 8: Rename the edited html to `2.html`
Step 9: Open terminal as admin (Win+X menu Terminal(Admin) will do), then enter the command `taskkill /f /im SearchHost.exe`
Step 10: Open the search function, wait for it loads and should successfully load the script if done right.

![image](https://user-images.githubusercontent.com/95956843/194476508-7ae8f2b1-3b66-483f-b637-6e1f0b3509bf.png)

**Comment by krlvm** [comment]
IDK why left pane has borders though, I will fix it soon
