### ISSUE TITLE
White scroll bar on dark theme

### ISSUE THREAD

**Issue by SeriousMOod** [krlvm/BeautySearch#32]
Dark theme, but white scrollbar. I don't know if this is a bug? If not, is it possible to make a dark scrollbar?
![Снимок экрана 2022-10-11 115715](https://user-images.githubusercontent.com/92377257/195000936-24ce0960-45be-417a-b46c-484e60ff3319.png)

**Comment by krlvm** [comment]
It is not possible to make it dark without having access to WebView APIs :(
