### ISSUE TITLE
When will there be a silent uninstall switch?

### ISSUE THREAD

**Issue by Zliced13** [krlvm/BeautySearch#33]
Hello @krlvm, I hope you are having a great day,

I want to ask, will there eventually be a silent uninstallation switch for the program? Or is there one already implemented in the program? If there is already an implementation, could you please tell me what it is?

**Comment by krlvm** [comment]
If I remember correctly, I've already implemented it, try this:
```
BeautySearch.exe Uninstall
```

**Comment by Zliced13** [comment]
When I execute the command, I get a GUI prompt that asks if I want to re-enable Bing search, which I don't want to do. Are there more parameters for the `Uninstall` argument that I am not aware of? 
![(WindowsTerminal)S0z6D7_11-01-2022](https://user-images.githubusercontent.com/101912712/199204125-d80ec6f7-a5ad-4a00-8238-02281fbe0cfe.jpg)

**Comment by krlvm** [comment]
You can use
```
BeautySearch.exe Uninstall -Silent
```
with [version 1.5.2](https://github.com/krlvm/BeautySearch/releases/tag/v1.15.2)
