### ISSUE TITLE
Light theme is not preserved after logout/reboot of Windows 10 version 21H2

### ISSUE THREAD

**Issue by bananakid** [krlvm/BeautySearch#36]
Windows 10 build 19044.1288. When using Light theme for both Windows and Search (via BeautySearh 1.15.2) and reboot/logout, the Search UI is being reset to Dark mode. However since text color of Light theme is black the Search UI becomes broken (until changed or reset via BeautySearch). Fake acrylic effect is being preserved as well as other settings. Is there any way to fix this somehow? I tried downgrading to 13.5 and that didn't help. When you use Dark theme everything's fine after logout/reboot... Oh, and if the Light theme is used the setting "Show accent color on Search Window" is not working (when applied only Light theme is being applied). However accent color appears with half-dark theme of Search after reboot/logout.

P.S. Here's a "Light" Search theme after logout a logging back in:

![Capture](https://user-images.githubusercontent.com/17095595/202233536-d9e4c848-1113-4320-9a92-cccb97b790dd.png)

**Comment by bananakid** [comment]
Oops, my bad, after turning on first [20H1+] option everything's working as it should. Sorry!

**Comment by krlvm** [comment]
I think they've changed popup menu class name recently, I'll check it.

**Comment by bananakid** [comment]
@krlvm Sorry for bugging, I dealt with the issue on my own (long story short, false positive). I had to edit the initial message of this thread as I faced different problem during extensive testing. Please have a look once you'll have a minute. Thank you for your tasteful tweaks.

**Comment by bananakid** [comment]
Thanks so much for taking time to make it clear. LTSC editions get only security updates, not possible to update build (likely, at all). This is the latest available LTSC of Windows 10 (Windows 10 Enterprise LTSC 2021 version 21H2). Do you think it is possible to get around by updating just Microsoft.Windows.Search with the more recent version? I noticed my current version is 2019.10.17.623201 but I can at least try swapping DLLs and EXE inside Windows/SystemApps/Microsoft.Windows.Search with the more recent ones.

**Comment by krlvm** [comment]
It is not a new build, just a cumulative update. Try checking for updates in the Windows Settings.

**Comment by bananakid** [comment]
Thanks for heads up, you're correct regarding the possibility of updating LTSC with cumulative update. However I manage multiple computers and would like to get away without applying entire cumulative update [KB5011543](https://support.microsoft.com/en-us/topic/march-22-2022-kb5011543-os-builds-19042-1620-19043-1620-and-19044-1620-preview-4fe2d1c0-720f-47fe-9523-75339bc107a1) because it may break something else (i.e Print Nightmare sort of thing in surprising place the time you need it the most).

So I downloaded update via [Update Catalog](https://www.catalog.update.microsoft.com/Search.aspx?q=KB5011543) and applied in my testing environment, version bumped up from 19044.1288 to 19044.1620. BeautySearch 1.15.2 got working correctly. Then I backed up C:\Windows\SystemApps\Microsoft.Windows.Search* contents that got changed by update. I restored snapshot of pre-updated OS and and manually replaced files with the new ones (running as TrustedInstaller). Acrylic effect in Search and everything else altered by BeautySearch appears to be working now (SearchApp version is old since I didn't bother to re-register AppX I guess):

![Result](https://user-images.githubusercontent.com/17095595/202364869-1d33b503-18a2-44e8-9c06-fe553dc00750.png)

Search is working as it should. However acrylic effect is not that pronounced and a lot of options I've seen in BeautySearch on updated OS 19044.1620 are missing. I see you can edit BeautySearch configuration via JS file. However I'm not sure how do I effectively reload configuration after JS file is altered. Would you kindly tell me how that's done manually?

There's two questions more if you will:
1) if possible would you kindly tell how to edit Top Apps manually since it's not working right now (no errors)?
2) would you kindly tell if there's a way to turn off OS version check in BeautySearch so that I could use UI later on?

P.S. I will provide fix files list for everyone with older builds later on (11 MB partial update vs 661 MB of cumulative update).
