### ISSUE TITLE
Installer is blurry on hidpi screen

### ISSUE THREAD

**Issue by Poopooracoocoo** [krlvm/BeautySearch#4]
![image](https://user-images.githubusercontent.com/51363864/91711169-cd629d00-ebc8-11ea-845f-7d5a04049ea8.png)

**Comment by krlvm** [comment]
I forgot to enable HiDPI screens support, you can use this registry tweak to get rid of this issues in the most of apps:
```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Control Panel\Desktop]
"Win8DpiScaling"=dword:00000001
"DpiScalingVer"=dword:00001018
"LogPixels"=dword:00000078
```
