### ISSUE TITLE
Icons for UWP apps are all the same

### ISSUE THREAD

**Issue by Ronzaigu** [krlvm/BeautySearch#40]
I installed it and a few days later every uwp apps have the paint 3d icon, i tried unistalling paint 3d but it was another app. Clearing the icon cache works but i have to do it every time i sign in into windows.
![image](https://user-images.githubusercontent.com/106442917/219867047-6ab95e65-76ba-4560-920f-a043092039a4.png)
How can i fix this or automatically clear the icon cache every time i start my pc or sign in with task scheduler ?

**Comment by krlvm** [comment]
To clear icon cache, you just need to delete `%LocalAppData%\Packages\Microsoft.Windows.Search_cw5n1h2txyewy\LocalState\AppIconCache` directory.

BeautySearch could not cause this, I remember having the same problem before I developed it, only there were Photos app icons instead of Paint 3D icons.

**Comment by Ronzaigu** [comment]
Thanks a lot !
