### ISSUE TITLE
Rounded borders and floating search menu for Windows 10

### ISSUE THREAD

**Issue by NorvinGZ** [krlvm/BeautySearch#41]
I would like to know if at some point they would put a shape for the search menu has rounded edges and is floating in windows 10 I feel that it would look more minimalist to attack that style since many not only to my likaria but entedere if this idea can not be carried out.

**Comment by NorvinGZ** [comment]
recently customize the start menu and I stay like this but with the design of the search menu does not agree anything
![image](https://user-images.githubusercontent.com/117472566/225079920-7c83013a-ff5b-48a4-9811-0a5a142d9079.png)

**Comment by krlvm** [comment]
This can't be done with BeautySearch, which only has access to the WebView inside the window, however, you can try to hook into it like ExplorerPatcher does with the Start menu.

**Comment by NorvinGZ** [comment]
Not with the image I only meant the basic style of the search menu.
since good is square
![image](https://user-images.githubusercontent.com/117472566/225131224-4c577973-f039-47ad-b83d-dc63a9c299a6.png)

**Comment by NorvinGZ** [comment]
But I still understand that it could not be done because of the work behind it.

**Comment by krlvm** [comment]
I mean, BeautySearch can't access the Window itself, it injects into the WebView, which is inside the Window.
