### ISSUE TITLE
BeautySearch fails after Update KB5027215 (Build 19044.3086 for 21H2, 19045.3086 for 22H2)

### ISSUE THREAD

**Issue by bywkgexmkiltxh** [krlvm/BeautySearch#46]
BeautySearch is unable to patch Windows Search, it ends up with the error _Unknown Error: -532462766_

**Comment by MehranAkbarii** [comment]
I have the same issue , please fix it , the windows 10 default search look so awful

**Comment by krlvm** [comment]
The error above disappears if you grant the permissions manually (described [here](https://github.com/krlvm/BeautySearch/issues/11#issuecomment-860113080)), but the next problem is inability to locate the Search App "controller" - some reverse-engineering is required to solve it - in general, this would have to be done after each update of Search, but for more than a year Microsoft managed not to make any major changes, so this hasn't been a problem before.

**Comment by MehranAkbarii** [comment]
thanks

**Comment by bywkgexmkiltxh** [comment]
> The error above disappears if you grant the permissions manually (described [here](https://github.com/krlvm/BeautySearch/issues/11#issuecomment-860113080))

Instead of doing this, I suggest whoever is reading here to install 7-zip, run it as administrator and run BeautySearch through 7-zip File Manager.

I think the problem is related to Microsoft integrating online search to offline search. To broach, the offline and the online search experiences used to be different. When the online search is disabled using Registry Editor, the search switched to a slightly different and less bundled interface; it absents transparent search results, its translation is slightly outdated, etc.
I'm on IoT Enterprise LTSC 2021 and the offline search results are transparent now just like the online search in vanilla 21H2 and 22H2. The only difference I've seen is basically Bing and the web results are unavailable. The rest is virtually same as the online search, which can be found in vanilla 21H2 and 22H2.

I'm not a developer but I know how to use a computer (pilot and aircraft engineer situation I think how it's correlated) and I'm suspecting that the offline search is now the online search, but the online part is disabled (both experiences are shared now).

**Comment by krlvm** [comment]
Weird, it's really work if it was started not via Explorer?

Search App is actually a web page and its local copy is present in each Windows installation. When Bing search is enabled, the page is being loaded from the internet

**Comment by krlvm** [comment]
I forgot to mention, this can be temporarily resolved by disabling "Controller Integration" tweak

**Comment by krlvm** [comment]
Fixed in [v1.16](https://github.com/krlvm/BeautySearch/releases/tag/v1.16), thanks for reporting
