### ISSUE TITLE
App no longer seems to work

### ISSUE THREAD

**Issue by nopahc4** [krlvm/BeautySearch#49]
Basically I set up the settings, then click install, the search app restarts but nothing changes, is it just me?

**Comment by krlvm** [comment]
I'll test it with the latest Windows 10 build soon

**Comment by nopahc4** [comment]
> I'll test it with the latest Windows 10 build soon

hows it going?

**Comment by nopahc4** [comment]
okay thanks

> Fixed in [version 1.17](https://github.com/krlvm/BeautySearch/releases/tag/v1.17)

It still doesn't want to work for me :(

**Comment by krlvm** [comment]
What error are you getting?

**Comment by nopahc4** [comment]
> What error are you getting?

Sorry for no reply I rarely use my laptop, so there's no error clicking install just opens the search app with no settings changed, only the bing thing dissapears

**Comment by krlvm** [comment]
Which build of Windows 10 are you running?

**Comment by nopahc4** [comment]
> Which build of Windows 10 are you running?

Windows 10 Home 22H2 19045.4046
