### ISSUE TITLE
UWP app icons are low res

### ISSUE THREAD

**Issue by Poopooracoocoo** [krlvm/BeautySearch#5]
Might have something to do with how BeautySearch resizes it and that UWP tiles have different sizes?

low res uwp app icon:
![image](https://user-images.githubusercontent.com/51363864/91713467-2b917f00-ebcd-11ea-9994-4634c6248610.png)

normal looking win32 app icon:
![image](https://user-images.githubusercontent.com/51363864/91713469-2cc2ac00-ebcd-11ea-98c5-d7b72319dff8.png)

**Comment by krlvm** [comment]
The problem is that system provides low-res UWP icons in order for them to be placed into frame later, this can't be solved at the moment.
