### ISSUE TITLE
Inaccurate theme switch

### ISSUE THREAD

**Issue by youpidou01** [krlvm/BeautySearch#6]
Not sure whether it's the case with my PC only, but every time I get to search something either by clicking magnifier icon in the taskbar or by pressing WIN key and start typing, search results initially appear in white background, and stays white all the way till you (left) click with a mouse pointer on that white background or one of the search result after which it immediately turns to black/dark as it was supposed to be.. then it stays dark.
White background is present after each boot only initially until you click on it

I'm running win10 with latest update

- here are some screenshots just for comparison

![image](https://user-images.githubusercontent.com/71134483/92930339-373d3b00-f442-11ea-977b-7e8ffa626264.png)
![image](https://user-images.githubusercontent.com/71134483/92930434-5b008100-f442-11ea-881c-60f5336df07e.png)

**Comment by krlvm** [comment]
The problem is that we need to maintain support of light and dark theme on the same time, and it's pretty hard to do in the real time without a background service running.
I can make a "dark-only" mode, but you will have to launch the BeautySearch Installer every time you want to switch search result theme.

**Comment by krlvm** [comment]
Disable this option in [version 1.2.2](https://github.com/krlvm/BeautySearch/releases/tag/v1.2.2) to solve your problem:
![Screenshot](https://user-images.githubusercontent.com/51774833/92937639-41683500-f454-11ea-976b-d1e04ea2b373.png)

**Comment by krlvm** [comment]
I reuploaded the release due to a GitHub internal problem.

**Comment by krlvm** [comment]
Finally fixed in [version 1.4](https://github.com/krlvm/BeautySearch/releases/tag/v1.4)
